# Generated by Django 3.2.16 on 2023-02-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_newcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('C', 'Camera'), ('K', 'Keyboards'), ('Mo', 'Mouse'), ('D', 'Desktops'), ('P', 'Pendrive')], default='M', max_length=10)),
                ('product_image', models.ImageField(upload_to='discount_images')),
            ],
        ),
        migrations.RenameField(
            model_name='newcollection',
            old_name='image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='newcollection',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='newcollection',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('C', 'Camera'), ('K', 'Keyboards'), ('Mo', 'Mouse'), ('D', 'Desktops'), ('P', 'Pendrive')], default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='newcollection',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='newcollection',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
