# Generated by Django 3.2.16 on 2023-05-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('C', 'Camera'), ('Cl', 'Cloth'), ('G', 'Grocery')], max_length=10),
        ),
    ]
